language: python
python:
  - 2.7
  - 3.6

env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0

matrix:
  exclude:
    - python: 3.6
      env: DJANGO=1.4
    - python: 3.6
      env: DJANGO=1.5
    - python: 3.6
      env: DJANGO=1.6
    - python: 3.6
      env: DJANGO=1.7
    - python: 2.7
      env: DJANGO=2.0

install:
  - pip install Django==$DJANGO
  - python setup.py develop
script:
  - python manage.py test tests
