language: python
sudo: required
dist: xenial

python:
  - 2.7
  - 3.6
  - 3.7

env:
  - DJANGO=1.11
  - DJANGO=2.1
  - DJANGO=2.2

matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.1
    - python: 2.7
      env: DJANGO=2.2
    - python: 3.7
      env: DJANGO=1.11

install:
  - pip install Django==$DJANGO
  - python setup.py develop
script:
  - python manage.py test tests
