dist: bionic
language: python

python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8

stages:
  - lint
  - tests

jobs:
  include:
    - stage: lint
      python: 3.6
      env: TOXENV=lint

install:
  - pip install tox
  - pip install -q tox-travis
script:
  - tox
